# .github/workflows/activity-graph.yml
name: generate activity graph

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Ashutosh00710/github-readme-activity-graph@v2.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          username: khushi-070906
          theme: tokyo-night
          output: github-contribution-grid-snake.svg
      - uses: actions/checkout@v3
      - run: git config user.name github-actions && git config user.email actions@github.com
      - run: git add . && git commit -m "update activity graph" && git push
