name: generate activity graph

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: generate graph
        uses: Ashutosh00710/github-readme-activity-graph@v1.3.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          username: khushi-070906
          theme: tokyo-night
          output: github-contribution-grid.svg

      - name: push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: update activity graph
          file_pattern: github-contribution-grid.svg
